export { isPnpEnabled, pnpApi } from './src/lib/pnp'
export { resolve } from './src/resolve'
export { resolveModule } from './src/resolveModule'
export { resolveSync } from './src/resolveSync'
export type { IModule, IResolveOptions } from './src/lib/interfaces'
